In [ ]:
# array
# -
# -
# -
# -
# -

# list



# -         ----------------------------------------->                     -
                



Python -->Day1

Data Analytics----> Pandas library


A collection of values---->e.g : 1 column of our data frame

Visualization --->plotly_express



# Multiple values in a single collection?


numpy array : store data in consecutive memory locations


integer array : only integer type of data

pandas uses numpy array in backend

In [1]:
import numpy as np

In [2]:
z1=np.zeros(20)
z1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [12]:
z1.dtype

dtype('float64')

In [4]:
zint1=np.zeros(10,dtype='int64')
print(zint1.dtype)

print(zint1)

int64
[0 0 0 0 0 0 0 0 0 0]


In [5]:
o1=np.ones(7)
print(o1)
print(o1.dtype)

[1. 1. 1. 1. 1. 1. 1.]
float64


In [9]:
l1=[     number   for number in range(1,51)            ]

# print(l1)

arr = np.array(   l1, dtype='int8'   )

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
      dtype=int8)

In [15]:
l1=[1,20,45,6,7,8,9,29]

arr1=np.array(l1,dtype='int64')
arr1

array([ 1, 20, 45,  6,  7,  8,  9, 29])

In [16]:
print(arr1.dtype)

int64


In [17]:
arr1.ndim

1

In [18]:
l1=[ [1,2],[3,4],[5,6] ]


arr2d=np.array(l1,dtype='int64')
arr2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
arr2d.ndim

2

In [20]:
arr2d.shape

(3, 2)

In [12]:
student1 =[    48,47,42     ]

student2 = [   40,32,39       ]

student3 = [     10,20,30        ]

#inserting lists in list
data =[    student1,  student2,    student3            ]

print(data)

arr = np.array(data)

[[48, 47, 42], [40, 32, 39], [10, 20, 30]]


In [15]:
import pandas as pd


pd.DataFrame(  arr.T, columns=['Ajay', 'Manoj', 'Ruhi']  )

Ajay  Manoj  Ruhi
0    48     40    10
1    47     32    20
2    42     39    30

In [17]:
d1={
    "name" : 'Harshit',
    "age" : 28
}

pd.DataFrame(d1, index=[0])

name  age
0  Harshit   28

In [29]:
employees = {
    "d1" : {
        "name" : 'Harshit',
        "age" : 28
    },

    "d2" : {
       "name" : "Ajay",
       "age" : 28 
    },

    "d3" : {
        "name" : "Manoj",
        "age" : 32
    }
}


df = pd.DataFrame(employees).T

df

name age
d1  Harshit  28
d2     Ajay  28
d3    Manoj  32

In [22]:
df['name']

d1    Harshit
d2       Ajay
d3      Manoj
Name: name, dtype: object

In [30]:
df['age'] = df['age'].astype('int64')

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, d1 to d3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 72.0+ bytes


In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, d1 to d3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   age     3 non-null      object
dtypes: object(2)
memory usage: 72.0+ bytes


In [33]:
arr2ddirect=np.array([ [50,2],[3,4],[5,6] ],dtype='int64')
arr2ddirect

array([[50,  2],
       [ 3,  4],
       [ 5,  6]])

In [34]:
arr2ddirect[0] #0th row

array([50,  2])

In [35]:
arr2ddirect[1] #1st row

array([3, 4])

In [36]:
arr2ddirect

array([[50,  2],
       [ 3,  4],
       [ 5,  6]])

In [25]:
arr2ddirect[2]    [1] #row 2 column 1

6

In [26]:
arr2ddirect[2,0]

5

In [38]:
arr2ddirect

array([[50,  2],
       [ 3,  4],
       [ 5,  6]])

In [37]:
arr2ddirect[ : ,   0]                     #all rows, 0th column

array([50,  3,  5])

In [40]:
temp=np.array(
    [
    
    [1,2,3,4],
    [10,20,30,40],
    [111,222,333,444]
    
    ]

)
temp

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [111, 222, 333, 444]])

In [41]:
temp.shape

(3, 4)

In [30]:
temp[   1    ,  1:3      ] #row 1, columns 1 less than 3

array([20, 30])

In [31]:
temp[   0:2   ,  2:3      ] #rows from 0 less than 2,   columns from 2 less than 3

array([[ 3],
       [30]])

In [32]:
temp.shape

(3, 4)

In [33]:
temp.size #number of elements

12

In [ ]:
# 2,6

1,12


4,3

6,2

12,1

In [42]:
temp

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [111, 222, 333, 444]])

In [ ]:
# 12 elements

"""
1 rows of 12 elements

2 rows of 6 elements each


3 rows of 4 elements each

4 rows of 3 elements each

6 rows of 2 elements each

12 rows of 1 element each
"""

# this will be used in ML model testing!!!!!!

In [34]:
np.reshape(temp, ( 6,2 )   ) # 6 rows of 2 elements each

array([[  1,   2],
       [  3,   4],
       [ 10,  20],
       [ 30,  40],
       [111, 222],
       [333, 444]])

In [35]:
np.reshape(temp, ( 12,1 )   ) # 12 rows , 1 column

array([[  1],
       [  2],
       [  3],
       [  4],
       [ 10],
       [ 20],
       [ 30],
       [ 40],
       [111],
       [222],
       [333],
       [444]])

####

        what is a numpy array?

        #create dummy data in a numpy array : ---> zeros, ones functions
        #check the shape of the array : ------> shape
        #the number of dimensions in the array ---> ndim
        # create an array from a list ------> numpy.array function
        # to check the data type of a numpy array ----> dtype
        # total number of elements in the numpy array --->size 
        # can we convert array of one arrangement to a different layout? ---> yes using reshape


# connection with our course outline?

    1) pandas data frame is made up of numpy arrays.
            # 1 array per column

    2) We can convert data from 1 type to another

In [ ]:

names = [harshit,Ajay,Manoj]

age=[20,30,45]

gender[Male,Male,Male]



harshit   20   Male
Ajay      30   Male
Manoj     45   Male






In [36]:
temp

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [111, 222, 333, 444]])

In [37]:
temp+temp #addition

array([[  2,   4,   6,   8],
       [ 20,  40,  60,  80],
       [222, 444, 666, 888]])

# index wise subtraction of 2 numpy arrays(open - close)

In [38]:
temp*temp

array([[     1,      4,      9,     16],
       [   100,    400,    900,   1600],
       [ 12321,  49284, 110889, 197136]])

In [39]:
temp

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [111, 222, 333, 444]])

In [40]:
other=np.reshape(temp, ( 12,1 )   )
other

array([[  1],
       [  2],
       [  3],
       [  4],
       [ 10],
       [ 20],
       [ 30],
       [ 40],
       [111],
       [222],
       [333],
       [444]])

In [43]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2,3])

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2

# [1, 2, 3][1, 2, 3]
# [4, 5, 6][1, 2, 3]

array([1, 2, 3])

In [47]:
np.random.randint(0,50,6,dtype='int')

array([19, 27, 15, 16, 11, 48])

In [46]:
arr1+arr2

array([[2, 4, 6],
       [5, 7, 9]])

In [41]:
temp+other

ValueError: operands could not be broadcast together with shapes (3,4) (12,1) 